language: cpp
compiler: clang
sudo: require
dist: trusty
before_install:
- sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
- sudo apt-get update -qq
install:
- sudo apt-get -y -qq install cmake ccache ninja-build
- sudo apt-get -y -qq install libgl1-mesa-dev qt59base qt59imageformats qt59svg qt59charts-no-lgpl qt59tools
- source /opt/qt*/bin/qt*-env.sh
before_script:
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_PREFIX_PATH=$QTDIR/bin -G Ninja ..
script:
- ninja -j $(nproc)
- lupdate ../stacer/stacer.pro
- lrelease ../stacer/stacer.pro
